title: Azure in the Enterprise
description: >- # this means to ignore newlines until "baseurl:"
  Adopting Azure in the context of an organization.
twitter_username: lyledodge
github_username: lyledodgepersonal

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
